name: Trigger cut-dana-platform-mp Build
on:
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify cut-dana-platform-mp
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: citysciencelab/cut-dana-platform-mp
          event-type: trigger-main-build
